# VeriBoard Customer Service - Base Configuration
# This file contains common configuration shared across all environments

spring:
  application:
    name: customer
  
  # JPA Base Configuration
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: false

  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

  # Cloud Configuration
  cloud:
    # Kubernetes Service Discovery Configuration
    kubernetes:
      discovery:
        all-namespaces: true # Discover services across all namespaces
        enabled: true # Enable Kubernetes service discovery
      loadbalancer:
        mode: SERVICE # Use Kubernetes Service names for load balancing
    compatibility-verifier:
      enabled: false

# Management and Monitoring
management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  tracing:
    enabled: true

# Logging Base Configuration
logging:
  level:
    tech.yump.veriboard: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"