apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: eXVtcHRlY2g=  # base64 encoded "yumptech"
  password: cGFzc3dvcmQ=  # base64 encoded "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  username: Z3Vlc3Q=      # base64 encoded "guest"
  password: Z3Vlc3Q=      # base64 encoded "guest" 