# VeriBoard Fraud Service - Production Environment Configuration
# This configuration extends application.yml for production deployment

server:
  port: 8081
  error:
    include-message: never
    include-stacktrace: never

spring:
  # Production Database Configuration
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  # JPA Production Settings
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    show-sql: false

  # Kubernetes Discovery Client Configuration (Production Specific, if any)
  # Common settings are inherited from base application.yml.
  # If you need to restrict discovery to specific namespaces in prod:
  # cloud:
  #   kubernetes:
  #     discovery:
  #       all-namespaces: false
  #       namespaces:
  #         - "veriboard-prod" # Example production namespace

# Production Monitoring and Security
management:
  # Zipkin endpoint is inherited from base, or can be overridden via ZIPKIN_TRACING_ENDPOINT env var
  # zipkin:
  #   tracing:
  #     endpoint: ${ZIPKIN_TRACING_ENDPOINT_PROD:http://zipkin.veriboard-prod.svc.cluster.local:9411/api/v2/spans}

  endpoint:
    health:
      show-details: never # Good for production
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    enabled: true # General tracing toggle
    sampling:
      probability: 0.1  # Sample 10% of traces in production

# Production Logging
logging:
  level:
    tech.yump.veriboard: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.springframework.security: WARN
  file:
    name: /var/log/veriboard/fraud.log # Ensure this path is writable by the application user in the container
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 3GB