server:
  port: 8083

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://desktop.local:9411
  cloud:
    # Kubernetes Service Discovery Configuration
    kubernetes:
      discovery:
        all-namespaces: true # Discover services across all namespaces
        enabled: true # Enable Kubernetes service discovery
      loadbalancer:
        mode: SERVICE # Use Kubernetes Service names for load balancing
    gateway:
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/api/v1/customers/**